### ISSUE TITLE
extracting arrays

### ISSUE THREAD

**Issue by fatihky** [aykutkardas/muninn#20]
queried elements may contain children with the same selector. we should allow people to define some fields as arrays.

example:
![image](https://user-images.githubusercontent.com/4169772/116669933-d9953900-a9a7-11eb-843d-9828b52139d4.png)

**Comment by aykutkardas** [comment]
**Related commit:** https://github.com/aykutkardas/muninn/commit/a836eb7b6a927845dd711ac9291b45901352ddcf
